# Data pre-processing

# Census Data

Data cover the entire Mexico City, but have a sub-unit (Manzana) that we do not consider. After importing, select AGEB, replace special character `*` with Nan values, select non-string objects and convert them into float data type. Save file.

In [1]:
import pandas as pd
import numpy as np

INEGI portal, inegi.org.mx, has been down for a while. Use the local version uploaded in GitHub.

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/cecilia-sartori/rainwater-reuse/main/data/RESAGEBURB_09XLSX20.csv')
df.head()

,CVEGEO,ENTIDAD,NOM_ENT,MUN,NOM_MUN,LOC,NOM_LOC,AGEB,MZA,POBTOT,...,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCINT,VPH_SINTIC
0,0900000000000,9,Ciudad de México,0,Total de la entidad Ciudad de México,0,Total de la entidad,0000,0,9209944,...,1898265,2536523,2084156,1290811,957162,568827,46172,77272,561128,10528
1,0900200000000,9,Ciudad de México,2,Azcapotzalco,0,Total del municipio,0000,0,432205,...,96128,123961,105899,66399,50965,31801,1661,2869,22687,322
2,0900200010000,9,Ciudad de México,2,Azcapotzalco,1,Total de la localidad urbana,0000,0,432205,...,96128,123961,105899,66399,50965,31801,1661,2869,22687,322
3,0900200010010,9,Ciudad de México,2,Azcapotzalco,1,Total AGEB urbana,0010,0,3183,...,741,772,692,313,221,145,8,14,148,5
4,0900200010010,9,Ciudad de México,2,Azcapotzalco,1,Azcapotzalco,0010,1,159,...,45,42,39,18,13,6,*,0,9,0

In [3]:
df = df[df['NOM_LOC']=='Total AGEB urbana']
df = df.replace('*', np.nan)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2433 entries, 3 to 68915
Columns: 231 entries, CVEGEO to VPH_SINTIC
dtypes: int64(6), object(225)
memory usage: 4.3+ MB

Most of the entries are set as objects. We need to convert them in numbers.

In [5]:
df1 = df.iloc[:,:9]
df2 = df.iloc[:,9:]

df2 = df2.fillna(0).astype(float)
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2433 entries, 3 to 68915
Columns: 222 entries, POBTOT to VPH_SINTIC
dtypes: float64(222)
memory usage: 4.1 MB

In [6]:
df = pd.concat([df1,df2], axis=1)

In [7]:
#Export 
#df.to_csv('data/census_data2020.csv', index = False)

# VAW Data

VAW data of Mexico City is included in the crime victim dataset. This means that I have to identify which rows are significant to the project based on the description of the crime and the victim's gender.

The data set is licensed under the open data licence (CC BY 4.0).

* Date source:

    [Crime victims complaints - Mexico City Open Data Portal](https://datos.cdmx.gob.mx/dataset/victimas-en-carpetas-de-investigacion-fgj)



* Data Structure:

    Structure of the data is described in a separate excel file ([download here](https://datos.cdmx.gob.mx/dataset/victimas-en-carpetas-de-investigacion-fgj/resource/10235569-f4a9-4876-9465-9780887df8e2))

In [8]:
!wget -P data/ https://archivo.datos.cdmx.gob.mx/fiscalia-general-de-justicia/victimas-en-carpetas-de-investigacion-fgj/victimas_completa_marzo_2022.csv

--2022-05-08 17:00:21--  https://archivo.datos.cdmx.gob.mx/fiscalia-general-de-justicia/victimas-en-carpetas-de-investigacion-fgj/victimas_completa_marzo_2022.csv
Resolving archivo.datos.cdmx.gob.mx (archivo.datos.cdmx.gob.mx)... 189.240.234.120
Connecting to archivo.datos.cdmx.gob.mx (archivo.datos.cdmx.gob.mx)|189.240.234.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 227953139 (217M) [text/csv]
Saving to: ‘data/victimas_completa_marzo_2022.csv’

victimas_completa_m 100%[===================>] 217.39M  16.0MB/s    in 17s

2022-05-08 17:00:39 (12.4 MB/s) - ‘data/victimas_completa_marzo_2022.csv’ saved [227953139/227953139]

In [9]:
# Read data
vaw = pd.read_csv('data/victimas_completa_marzo_2022.csv')
vaw.head()

,idCarpeta,Año_inicio,Mes_inicio,FechaInicio,Delito,Categoria,Sexo,Edad,TipoPersona,CalidadJuridica,...,Mes_hecho,FechaHecho,HoraHecho,HoraInicio,AlcaldiaHechos,ColoniaHechos,Calle_hechos,Calle_hechos2,latitud,longitud
0,8324429.0,2019.0,Enero,04/01/2019,FRAUDE,DELITO DE BAJO IMPACTO,Masculino,62.0,FISICA,OFENDIDO,...,Agosto,29/08/2018,12:00:00,12:19:00,ALVARO OBREGON,GUADALUPE INN,INSUGENTES SUR,NaN,19.36125,-99.18314
1,8324430.0,2019.0,Enero,04/01/2019,"PRODUCCIÓN, IMPRESIÓN, ENAJENACIÓN, DISTRIBUCI...",DELITO DE BAJO IMPACTO,Femenino,38.0,FISICA,VICTIMA Y DENUNCIANTE,...,Diciembre,15/12/2018,15:00:00,12:20:00,AZCAPOTZALCO,VICTORIA DE LAS DEMOCRACIAS,AV. CUATLAHUAC,NaN,19.47181,-99.16458
2,8324431.0,2019.0,Enero,04/01/2019,ROBO A TRANSEUNTE SALIENDO DEL BANCO CON VIOLE...,ROBO A CUENTAHABIENTE SALIENDO DEL CAJERO CON ...,Masculino,42.0,FISICA,VICTIMA Y DENUNCIANTE,...,Diciembre,22/12/2018,15:30:00,12:23:00,COYOACAN,COPILCO UNIVERSIDAD ISSSTE,COPILCO,NaN,19.33797,-99.18611
3,8324435.0,2019.0,Enero,04/01/2019,ROBO DE VEHICULO DE SERVICIO PARTICULAR SIN VI...,ROBO DE VEHÍCULO CON Y SIN VIOLENCIA,Masculino,35.0,FISICA,VICTIMA Y DENUNCIANTE,...,Enero,04/01/2019,06:00:00,12:27:00,IZTACALCO,AGRÍCOLA PANTITLAN,CALLE 6,ENTRE PRIVADA DEL VALLE Y PRIVADA GONZALEZ,19.40327,-99.05983
4,8324438.0,2019.0,Enero,04/01/2019,ROBO DE MOTOCICLETA SIN VIOLENCIA,ROBO DE VEHÍCULO CON Y SIN VIOLENCIA,Masculino,NaN,FISICA,VICTIMA,...,Enero,03/01/2019,20:00:00,12:35:00,IZTAPALAPA,PROGRESISTA,UNIVERSIDAD,NaN,19.35480,-99.06324

Inspect with info() method to get better data insight.

In [10]:
vaw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780439 entries, 0 to 780438
Data columns (total 22 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   idCarpeta        780439 non-null  float64
 1   Año_inicio       780438 non-null  float64
 2   Mes_inicio       780438 non-null  object
 3   FechaInicio      780438 non-null  object
 4   Delito           780439 non-null  object
 5   Categoria        780439 non-null  object
 6   Sexo             628287 non-null  object
 7   Edad             495406 non-null  float64
 8   TipoPersona      774405 non-null  object
 9   CalidadJuridica  780438 non-null  object
 10  competencia      780439 non-null  object
 11  Año_hecho        780120 non-null  float64
 12  Mes_hecho        780120 non-null  object
 13  FechaHecho       780120 non-null  object
 14  HoraHecho        780130 non-null  object
 15  HoraInicio       780438 non-null  object
 16  AlcaldiaHechos   779234 non-null  object
 17  ColoniaHechos    745330 non-null  object
 18  Calle_hechos     778237 non-null  object
 19  Calle_hechos2    280532 non-null  object
 20  latitud          745544 non-null  float64
 21  longitud         745542 non-null  float64
dtypes: float64(6), object(16)
memory usage: 131.0+ MB

There are 679 500 observations, which are quite a lot! Notice that the non-null values of latitude and longitude are less than the total entries. Therefore, drop all rows that have a NaN value in these columns and run a preliminary sub-selection by keeping female victims and latest year available.

From the data structure, I know that "Ano_inicio" field corresponds to the opening date of the investigation, while "Ano_hecho" represents the date on which the crime was committed. Then, go for the second.

In [11]:
# drop Nan values
vaw = vaw.dropna(subset=['latitud', 'longitud'])

# sort unique years in the data
year = sorted(vaw['Año_hecho'].unique())
print("Last year available: ", year[-1])

Last year available:  2022.0

Filter data accordingly

In [12]:
vaw = vaw[vaw['Año_hecho']== 2021]
vaw = vaw[vaw['Sexo']=='Femenino']

**Abortion in Mexico: a Crime?**

Since 2021, abortion in Mexico is no longer a crime, although its legalisation still varies by state ([source](https://edition.cnn.com/2021/09/07/americas/mexico-criminalizing-abortion-unconstitutional-intl-latam/index.html)). 

Yet, in our data it still labeled as a crime:

In [13]:
vaw[vaw['Delito']== 'ABORTO'].sample(1)

,idCarpeta,Año_inicio,Mes_inicio,FechaInicio,Delito,Categoria,Sexo,Edad,TipoPersona,CalidadJuridica,...,Mes_hecho,FechaHecho,HoraHecho,HoraInicio,AlcaldiaHechos,ColoniaHechos,Calle_hechos,Calle_hechos2,latitud,longitud
617883,8984123.0,2021.0,Julio,30/07/2021,ABORTO,DELITO DE BAJO IMPACTO,Femenino,NaN,FISICA,VICTIMA,...,Julio,30/07/2021,12:00:00,12:19:00,IZTAPALAPA,AMPLIACIÓN EMILIANO ZAPATA,CUCO SANCHEZ,NaN,19.338769,-98.976155

Considering abortion as a crime is beyond the scope of this project, but you too may find this interesting. 

**Back to Data Preparation**

Select vaw crimes that match with the strings "sexual, domestic, femicide" and then print the results.

In [14]:
vaw = vaw[vaw['Delito'].str.contains('sexual|familiar|feminicidio', case=False)]

print('List of crimes after text query:\n', vaw['Delito'].unique())

List of crimes after text query:
 ['VIOLENCIA FAMILIAR' 'ABUSO SEXUAL' 'ACOSO SEXUAL'
 'CONTRA LA INTIMIDAD SEXUAL' 'ACOSO SEXUAL AGRAVADO EN CONTRA DE MENORES'
 'FEMINICIDIO' 'FEMINICIDIO POR ARMA BLANCA' 'TENTATIVA DE FEMINICIDIO'
 'FEMINICIDIO POR DISPARO DE ARMA DE FUEGO'
 'PRIVACION DE LA LIBERTAD PERSONAL (REALIZAR ACTO SEXUAL)'
 'FEMINICIDIO POR GOLPES']

Using str.contains() as filter method in data preparation is highly not recommended because the chance of missing important information is real. For example, strings can have special characters. In this case, I didn't find any viable alternative.

Let's now begin to translate the DataFrame from Spanish to English starting from the columns names:

In [15]:
# select columns and rename
vaw = vaw[['FechaHecho', 'Delito', 'latitud', 'longitud']]
vaw.columns = ['Time', 'Crime', 'latitude', 'longitude']

In [16]:
vaw

              Time               Crime   latitude  longitude
480286  01/01/2021  VIOLENCIA FAMILIAR  19.198153 -99.026277
480289  01/01/2021  VIOLENCIA FAMILIAR  19.193027 -99.095006
480302  01/01/2021  VIOLENCIA FAMILIAR  19.336963 -99.152265
480306  01/01/2021  VIOLENCIA FAMILIAR  19.561525 -99.146590
480320  01/01/2021  VIOLENCIA FAMILIAR  19.395045 -99.061060
...            ...                 ...        ...        ...
779813  08/12/2021        ABUSO SEXUAL  19.282468 -99.010266
780165  31/03/2021  VIOLENCIA FAMILIAR  19.371821 -99.071966
780166  01/12/2021  VIOLENCIA FAMILIAR  19.259511 -99.101052
780286  19/07/2021        ABUSO SEXUAL  19.352580 -99.019935
780320  12/12/2021        ABUSO SEXUAL  19.325796 -99.069686

[31613 rows x 4 columns]

and continuing with the body. List all the values for 'Crime':

In [17]:
vaw['Crime'].unique()

array(['VIOLENCIA FAMILIAR', 'ABUSO SEXUAL', 'ACOSO SEXUAL',
       'CONTRA LA INTIMIDAD SEXUAL',
       'ACOSO SEXUAL AGRAVADO EN CONTRA DE MENORES', 'FEMINICIDIO',
       'FEMINICIDIO POR ARMA BLANCA', 'TENTATIVA DE FEMINICIDIO',
       'FEMINICIDIO POR DISPARO DE ARMA DE FUEGO',
       'PRIVACION DE LA LIBERTAD PERSONAL (REALIZAR ACTO SEXUAL)',
       'FEMINICIDIO POR GOLPES'], dtype=object)

Several types of 'FEMICIDE' are in. I use a simple regular expression to join them and replace them with the English word.

In [18]:
vaw['Crime'] = vaw['Crime'].str.replace(r'.*FEMINICIDIO.*', r'FEMICIDE', regex = True)

Conclude the translation for the other crime types.

In [19]:
from_text = ['VIOLENCIA FAMILIAR', 'ABUSO SEXUAL', 'ACOSO SEXUAL',
             'CONTRA LA INTIMIDAD SEXUAL', 'ACOSO SEXUAL AGRAVADO EN CONTRA DE MENORES',
             'FEMICIDE', 'PRIVACION DE LA LIBERTAD PERSONAL (REALIZAR ACTO SEXUAL)']

replace_with = ['DOMESTIC VIOLENCE', 'SEXUAL ABUSE', 'SEXUAL HARASSMENT',
        'AGAINST SEXUAL INTIMACY', 'AGGRAVATED SEXUAL HARASSMENT AGAINST MINORS', 'FEMICIDE',
        'DEPRIVATION OF PERSONAL LIBERTY (PERFORMING A SEXUAL ACT)']

vaw = vaw.replace(dict(zip(from_text, replace_with)))

In [20]:
vaw.head()

              Time              Crime   latitude  longitude
480286  01/01/2021  DOMESTIC VIOLENCE  19.198153 -99.026277
480289  01/01/2021  DOMESTIC VIOLENCE  19.193027 -99.095006
480302  01/01/2021  DOMESTIC VIOLENCE  19.336963 -99.152265
480306  01/01/2021  DOMESTIC VIOLENCE  19.561525 -99.146590
480320  01/01/2021  DOMESTIC VIOLENCE  19.395045 -99.061060

In [21]:
#Export data
#vaw.to_csv('data/vaw_filtered.csv', index = False)

# Neighbourhood

Add to neighbourhood variables the total population per unit by merging with 'Population per Neighbourhood'.

* Date source:

  [CDMX neighborhoods - Mexico City Open Data Portal](https://datos.cdmx.gob.mx/dataset/alcaldias/resource/8648431b-4f34-4f1a-a4b1-19142f944300)

* Data Structure:

  Structure of the data is described in a separate excel file [download here](https://datos.cdmx.gob.mx/dataset/alcaldias/resource/e4a9b05f-c480-45fb-a62c-6d4e39c5180e)

In [22]:
%%capture
!pip install rtree==0.9.7
!pip install mapclassify==2.4.3
!pip install geopandas==0.10.2

In [23]:
import geopandas as gpd

In [24]:
!wget -P data/ https://datos.cdmx.gob.mx/dataset/bae265a8-d1f6-4614-b399-4184bc93e027/resource/8648431b-4f34-4f1a-a4b1-19142f944300/download/alcaldias_cdmx.zip
!unzip data/alcaldias_cdmx.zip -d data/

--2022-05-08 17:01:00--  https://datos.cdmx.gob.mx/dataset/bae265a8-d1f6-4614-b399-4184bc93e027/resource/8648431b-4f34-4f1a-a4b1-19142f944300/download/alcaldias_cdmx.zip
Resolving datos.cdmx.gob.mx (datos.cdmx.gob.mx)... 45.60.240.232
Connecting to datos.cdmx.gob.mx (datos.cdmx.gob.mx)|45.60.240.232|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 176961 (173K) [application/octet-stream]
Saving to: ‘data/alcaldias_cdmx.zip’

alcaldias_cdmx.zip  100%[===================>] 172.81K  --.-KB/s    in 0.1s

2022-05-08 17:01:06 (1.52 MB/s) - ‘data/alcaldias_cdmx.zip’ saved [176961/176961]

Archive:  data/alcaldias_cdmx.zip
   creating: data/alcaldías_cdmx/
  inflating: data/__MACOSX/._alcaldías_cdmx
  inflating: data/alcaldías_cdmx/alcaldias_cdmx.dbf
  inflating: data/alcaldías_cdmx/alcaldias_cdmx.shx
  inflating: data/alcaldías_cdmx/alcaldias_cdmx.shp
  inflating: data/alcaldías_cdmx/alcaldias_cdmx.prj

In [25]:
# Read the data
gdf = gpd.read_file('data/alcaldías_cdmx/alcaldias_cdmx.shp')
gdf = gdf.rename(columns = {'nomgeo':'NOMGEO'})
gdf.head(5)

,X_id,id,NOMGEO,cve_mun,cve_ent,cvegeo,g_pnt_2,geo_shp,municip,geometry
0,1,0,MILPA ALTA,9,9,9009,"19.1394565999,-99.0510954218","{""type"": ""Polygon"", ""coordinates"": [[[-98.9972...",9,"POLYGON ((-98.99723 19.22731, -98.99745 19.227..."
1,2,1,BENITO JUÁREZ,14,9,9014,"19.3806424162,-99.1611346584","{""type"": ""Polygon"", ""coordinates"": [[[-99.1367...",14,"POLYGON ((-99.13679 19.40156, -99.13682 19.401..."
2,3,2,GUSTAVO A. MADERO,5,9,9005,"19.5040652077,-99.1158642087","{""type"": ""Polygon"", ""coordinates"": [[[-99.1185...",5,"POLYGON ((-99.11860 19.58446, -99.11691 19.581..."
3,4,3,COYOACÁN,3,9,9003,"19.3266672536,-99.1503763525","{""type"": ""Polygon"", ""coordinates"": [[[-99.1392...",3,"POLYGON ((-99.13923 19.35687, -99.13772 19.356..."
4,5,4,MIGUEL HIDALGO,16,9,9016,"19.4280623649,-99.2045669144","{""type"": ""Polygon"", ""coordinates"": [[[-99.1905...",16,"POLYGON ((-99.19058 19.46794, -99.19066 19.465..."

**Population per Neighbourhood**

* Date source:

  [CDMX Population per Neighbourhood - Mexico City Open Data Portal](https://datos.cdmx.gob.mx/dataset/poblacion-total-y-tasa-de-crecimiento-media-anual-1990-2020-por-alcaldia)


* Data Structure:

  Structure of the data is described in a separate excel file [download here](https://datos.cdmx.gob.mx/dataset/poblacion-total-y-tasa-de-crecimiento-media-anual-1990-2020-por-alcaldia/resource/ffa231fc-e0d2-4583-8a99-fd421fc9b442)

In [26]:
!wget -P data/ https://datos.cdmx.gob.mx/dataset/91ae7d55-af8f-410b-b93f-a819d2e8e95c/resource/15eed518-ee91-4ef4-ab18-ef83d831dcdd/download/poblacion_total_tasa_crecimiento_1.1.csv

--2022-05-08 17:01:07--  https://datos.cdmx.gob.mx/dataset/91ae7d55-af8f-410b-b93f-a819d2e8e95c/resource/15eed518-ee91-4ef4-ab18-ef83d831dcdd/download/poblacion_total_tasa_crecimiento_1.1.csv
Resolving datos.cdmx.gob.mx (datos.cdmx.gob.mx)... 45.60.240.232
Connecting to datos.cdmx.gob.mx (datos.cdmx.gob.mx)|45.60.240.232|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3583 (3.5K) [application/octet-stream]
Saving to: ‘data/poblacion_total_tasa_crecimiento_1.1.csv’

poblacion_total_tas 100%[===================>]   3.50K  --.-KB/s    in 0s

2022-05-08 17:01:07 (30.9 MB/s) - ‘data/poblacion_total_tasa_crecimiento_1.1.csv’ saved [3583/3583]

In [27]:
df = pd.read_csv('data/poblacion_total_tasa_crecimiento_1.1.csv')
df = df[df['Año'] == 2020]
df = df.reset_index(drop=True)
#df

In [28]:
# drop the last summary row
df = df.drop([16])
df = df.rename(columns = {'Alcaldia':'NOMGEO', 'Población total': 'POBTOT' })
df = df.apply(lambda x: x.astype(str).str.upper())

In [29]:
merge = gdf.merge(df, on='NOMGEO')
merge = merge.rename(columns = {'cvegeo':'CVEGEO'})
merge['POBTOT'] = merge['POBTOT'].str.replace(',', '').astype(int)

In [30]:
gdf = merge[['CVEGEO', 'NOMGEO', 'POBTOT', 'geometry']]
gdf.head()

,CVEGEO,NOMGEO,POBTOT,geometry
0,9009,MILPA ALTA,152685,"POLYGON ((-98.99723 19.22731, -98.99745 19.227..."
1,9014,BENITO JUÁREZ,434153,"POLYGON ((-99.13679 19.40156, -99.13682 19.401..."
2,9005,GUSTAVO A. MADERO,1173351,"POLYGON ((-99.11860 19.58446, -99.11691 19.581..."
3,9003,COYOACÁN,614447,"POLYGON ((-99.13923 19.35687, -99.13772 19.356..."
4,9016,MIGUEL HIDALGO,414470,"POLYGON ((-99.19058 19.46794, -99.19066 19.465..."

In [31]:
# Write to GeoJSON

#gdf.to_file("data/CDMX_municipalities.gjson", driver="GeoJSON")